### ISSUE TITLE
Need a pre-trained model.

### ISSUE THREAD

**Issue by Mohsin81** [choyi0521/snake-reinforcement-learning#2]
Hey can you upload your trained models for the the levels? Also, you mind telling me how long does it take for training one myself? it seems to be taking reaaaallly long.

**Comment by choyi0521** [comment]
Regrettably, I did not retain any checkpoints of this project.
As I remember the training finished within a day with a single GTX 1060, the model may be replicable without excessive computational resources.

I'm currently busy with other things, so it'd be nice if someone could test it.
